spring:
  application:
    name: starto-api
  datasource:
    url: jdbc:postgresql://localhost:5432/starto
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: user
    password: password
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8081

openai:
  api-key: ${OPENAI_API_KEY:dummy_key}

google:
  ai:
    api-key: ${GEMINI_API_KEY:AIzaSyA629ErsahC4X340k129_GZraW6BcQ6Lh8}
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY:AIzaSyDKFYLZS7YUysjKu-rnKKK3VA-kGh3R2Fk}

firebase:
  config-path: ${FIREBASE_CONFIG_PATH:src/main/resources/firebase-service-account.json}

razorpay:
  key:
    id: ${RAZORPAY_KEY_ID:rzp_live_SetihMoannIew3}
    secret: ${RAZORPAY_KEY_SECRET:0xIGSxuobSuqpt2u2s3K4bKN}
  plans:
    sprint: plan_Sf2GSCBf5wTrzk
    boost: plan_Sf2GSCBf5wTrzk
    pro: plan_Sf2GSCBf5wTrzk
    captain: plan_Sf2GSCBf5wTrzk
    captainPro: plan_Sf2GSCBf5wTrzk
    proPlus: plan_Sf2GSCBf5wTrzk
    growth: plan_Sf2GSCBf5wTrzk
    annual: plan_Sf2GSCBf5wTrzk